name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run:
          npm run build -- -ci
        env:
          NODE_TOKEN: ${{ secrets.NPM_TOKEN }}



# name: Package Publishing CI/CD

# on: [push]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}

#     # - name: Install dependencies
#       # run: npm ci

#     # - name: Run tests
#     #   run: npm test

#     - name: Publish to GitHub Packages
#       # if: github.ref == 'refs/heads/main' - enable me!
#       run:
#         npm run build -- -ci
#       env:
#         NODE_TOKEN: ${{ secrets.NPM_TOKEN }}

